version: '3.1'

services:
  contao:
    image: andypieters/contao:4.8
    restart: always
    ports:
      - 8000:80
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: contao
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: db
      MYSQL_PASS: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
