version: '3.1'

services:
  contao:
    image: andypieters/contao:4.8
    restart: always
    ports:
      - 8000:80
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: contao
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:8080